### ISSUE TITLE
Query Counter app can't update settings

### ISSUE THREAD

**Issue by gmonahan** [RallyCommunity/query-counter#15]
I use the TS Query Counter app a lot. It gives me a quick pulse on changes and errors and where I need to help teams with data accuracy.

Something changed in the last week. I am no longer able to select the App Settings from the menu to make changes to the variables or the page layout that displays the variables and other static text.

**Comment by krmorse** [comment]
Please follow up with Rally support for this issue.  Thanks!

**Comment by gmonahan** [comment]
Rally reverted some code from yesterday.
