### ISSUE TITLE
Would it be possible to allow for mathematical operations?

### ISSUE THREAD

**Issue by sficarrotta** [RallyCommunity/query-counter#3]
It would be great to show % stuff. For example, something like "{storyCount/storiesAccepted} % Stories Accepted" in the rich text area

**Comment by krmorse** [comment]
Yep!  Some smart folks already figured out this should just work out of the box since it uses an Ext.XTemplate under the hood.

So, for your example, this should work: {[ values.storiesAccepted / values.storyCount ]} % Stories Accepted
