### ISSUE TITLE
The math part of the templates isn't working as described

### ISSUE THREAD

**Issue by gmonahan** [RallyCommunity/query-counter#6]
Simple math like {var1 * 10} or {var2 / 10} work fine.
Using 2 variables like {var1 * var2} do not work. Various attempts at adding/removing spaces around the curly braces don't make a difference.

**Comment by krmorse** [comment]
From the docs here: https://github.com/RallyCommunity/query-counter#pro-tip

How about this?

`{[ values.var1 * values.var2 ]}`

**Comment by gmonahan** [comment]
No, that just displayed the equation text rather than calculated it. I
tried various permutations removing/adding spaces before the operator and
thecsquare brackets.

**Comment by krmorse** [comment]
Hmm, I just tested the above and was able to get it to work for me.  Are you using the app from the community catalog in the product?  Or a custom html version of it?  If the latter, are you sure you have the most recent code?

I wonder if it's possible that there is some formatting in your settings that is causing it to not recognize the formula as an expression to evaluate?

Can you maybe share a screenshot of what your settings look like?

**Comment by gmonahan** [comment]
Wait

I didn’t see the values. before the variable name. That works. Will change
my formulas and keep testing.

Thanks!!

**Comment by gmonahan** [comment]
Is there a way to get more than the count for a query type? I'd like to get the total number of todo hours for un-Accepted US's as a percentage of all US's - to get another validation of "percent complete" as all US's are not created equal.

**Comment by krmorse** [comment]
Right now count is the only aggregation that is supported.  That's a neat idea though.  I'm going to close this issue since it seems you were able to move forward and I'll open another one with the idea for additional aggregations- sum, avg, max/min, etc.
