### ISSUE TITLE
Bad link targeting

### ISSUE THREAD

**Issue by ewnash** [RallyCommunity/query-counter#9]
Same issue as in a previous build of the Rich Text App at https://github.com/RallyCommunity/rich-text-app. Hyperlinks open in the app instead of in a new tab/window.

**Comment by krmorse** [comment]
@ewnash I think I got it fixed, along with another timing issue where sometimes the save/cancel buttons are hidden.  Want to test this in html format and see if it works for you?

https://raw.githubusercontent.com/RallyCommunity/query-counter/28d2e0b8ff508dbe4a2539e5f1a0762c52047e6d/deploy/App-uncompressed.html

If so I'll get this merged here and try to get it promoted in the in-product community app catalog soon.

**Comment by ewnash** [comment]
Tested and looks good on both fronts, thanks @krmorse !
